name: CI
on: [push]
jobs:
  standard-checks: 
    name: Lint and Test
    runs-on: ubuntu-latest
    # runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      
      - name: Install packages
        run: npm ci
      - name: Run Eslint
        run: npm run ci:lint
      - name: Run Tests
        run: npm run ci:test
      - name: Lighthouse Benchmarks
        run: npm run ci:lighthouse