name: CI
on: [push]
jobs:
  eslint: 
    name: Lint Code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Run Eslint
        run: npm run ci:lint
      - name: Run Tests
        run: npm run ci:test